# samples.tsv, units.tsv, and deseq2_samples.tsv should be in working
#   directory as to keep track of each experiment's design

samples: samples.tsv
units: units.tsv


ref:
  name: dm6
  genome: /Volumes/Bioinfo_Ext/genomes/dmel_genome/bowtie_index/dm_6.ucsc.index

processing:
  remove-duplicates: true

params:
  trim-galore:
    options: "-j 4" # make sure cores match
    cores: 4
  bowtie2:
    options: "--very-sensitive-local -X 2000"
    cores: 8
  samtools-sort:
    options: "-m 4G"
    cores: 8
  samtools-view:
    options: "-b -@ 4 -h -q 30 chr2L chr2R chr3L chr3R chrX" # make sure cores match
    cores: 4
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  macs2:
    options: "-f BAM -g dm --nomodel --shift -37 --extsize 73 --call-summits --keep-dup all"
  bam-coverage:
    options: "--extendReads"

deseq2:
  samples: deseq2_samples.tsv
  contrasts:
    treated-vs-untreated:
      - treated
      - untreated
  pval: 0.1

pca:
  labels:
    - condition
